# Generated by Django 5.0.10 on 2025-01-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='unique_code',
        ),
    ]
