# Generated by Django 5.0.10 on 2025-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_rename_user_id_customuser_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
