# Generated by Django 5.0.10 on 2025-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_remove_course_student_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
