# Generated by Django 5.0.10 on 2025-03-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_alter_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='enrolled_student',
        ),
    ]
