# Generated by Django 5.0.10 on 2025-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_rename_student_course_enrolled_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enrolled_student',
            new_name='enrolled_students',
        ),
    ]
